//USERS ACTIONS
const ADD_USER = "ADD_USER";
const REMOVE_USER = "REMOVE_USER";
const LOGIN_USER = "LOGIN_USER";


//ITEMS ACTIONS
const ADD_ITEM = "ADD_ITEM";
const DELETE_ITEM = "DELETE_ITEM";
const GET_ONE_ITEM = "GET_ONE_ITEM";
const GET_ITEMS = "GET_ITEMS";
const GET_ALL_ITEMS_IN_CATEGORY = "GET_ALL_ITEMS_IN_CATEGORY";
const EDIT_ITEM = "EDIT_ITEM";

export const userActions = {
    ADD_USER,
    REMOVE_USER,
    LOGIN_USER,
}

export const itemActions = {
    ADD_ITEM,
    DELETE_ITEM,
    GET_ITEMS,GET_ONE_ITEM,
    GET_ALL_ITEMS_IN_CATEGORY,
    EDIT_ITEM,
}
